import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { SITE_CONFIG } from '../core/site.config';
import { buildWhatsAppUrl } from '../core/whatsapp';

@Component({
  selector: 'app-contact', imports: [ReactiveFormsModule],
  template: `
    <section class="page-hero contact-hero"><div class="container"><span>Parlons de vos envies</span><h1>Contactez Zakiya Bio</h1><p>Une question sur un produit ou sa disponibilité ? Notre équipe est à votre écoute.</p></div></section>
    <section class="section"><div class="container contact-layout"><div class="contact-info"><span class="eyebrow">Restons en contact</span><h2>Nous sommes là pour vous conseiller</h2><p>Choisissez le numéro WhatsApp qui vous convient. Les informations envoyées via le formulaire ouvriront WhatsApp : aucun message n’est transmis automatiquement par ce site.</p><div class="info-list"><a [href]="quickWhatsapp" target="_blank" rel="noopener"><b>◉</b><span><small>WhatsApp principal</small>{{ config.whatsapp }}</span></a><a [href]="secondaryWhatsapp" target="_blank" rel="noopener"><b>◉</b><span><small>WhatsApp secondaire</small>{{ config.whatsappSecondary }}</span></a>@if (config.address) {<div><b>⌖</b><span><small>Adresse</small>{{ config.address }}</span></div>}@if (config.email) {<a [href]="'mailto:' + config.email"><b>✉</b><span><small>E-mail</small>{{ config.email }}</span></a>}</div><div class="whatsapp-card"><span>◉</span><div><h3>Besoin d’une réponse rapide ?</h3><p>Échangez directement avec nous sur WhatsApp.</p></div><a class="btn btn-light" [href]="quickWhatsapp" target="_blank" rel="noopener">Démarrer la conversation</a></div></div>
      <div class="form-card"><span class="eyebrow">Votre demande</span><h2>Écrivez-nous</h2><form [formGroup]="form" (ngSubmit)="submit()" novalidate><div class="form-row"><label>Nom <em>*</em><input formControlName="lastName" autocomplete="family-name" [class.invalid]="invalid('lastName')">@if (invalid('lastName')) {<small>Indiquez au moins 2 caractères.</small>}</label><label>Prénom <em>*</em><input formControlName="firstName" autocomplete="given-name" [class.invalid]="invalid('firstName')">@if (invalid('firstName')) {<small>Indiquez au moins 2 caractères.</small>}</label></div><label>E-mail <em>*</em><input type="email" formControlName="email" autocomplete="email" placeholder="vous@exemple.com" [class.invalid]="invalid('email')">@if (invalid('email')) {<small>Saisissez une adresse e-mail valide.</small>}</label><label>Téléphone <span>(facultatif)</span><input type="tel" formControlName="phone" autocomplete="tel"></label><label>Sujet <em>*</em><select formControlName="subject" [class.invalid]="invalid('subject')"><option value="">Sélectionnez un sujet</option><option>Disponibilité d’un article</option><option>Conseil produit</option><option>Commande</option><option>Autre demande</option></select>@if (invalid('subject')) {<small>Choisissez un sujet.</small>}</label><label>Message <em>*</em><textarea rows="5" formControlName="message" placeholder="Comment pouvons-nous vous aider ?" [class.invalid]="invalid('message')"></textarea>@if (invalid('message')) {<small>Votre message doit contenir au moins 10 caractères.</small>}</label><button class="btn btn-primary btn-wide" type="submit">Continuer sur WhatsApp →</button><p class="form-note">En cliquant, WhatsApp s’ouvrira avec votre message préparé. Vous devrez confirmer son envoi.</p></form></div></div></section>
  `,
})
export class ContactComponent {
  private readonly fb = inject(FormBuilder); readonly config = SITE_CONFIG; readonly submitted = signal(false); readonly quickWhatsapp = buildWhatsAppUrl('Bonjour Zakiya Bio, je souhaite obtenir des informations.'); readonly secondaryWhatsapp = `https://wa.me/${SITE_CONFIG.whatsappSecondaryDigits}?text=${encodeURIComponent('Bonjour Zakiya Bio, je souhaite obtenir des informations.')}`; readonly form = this.fb.nonNullable.group({ lastName: ['', [Validators.required, Validators.minLength(2)]], firstName: ['', [Validators.required, Validators.minLength(2)]], email: ['', [Validators.required, Validators.email]], phone: [''], subject: ['', Validators.required], message: ['', [Validators.required, Validators.minLength(10)]] });
  invalid(name: keyof typeof this.form.controls): boolean { const c = this.form.controls[name]; return c.invalid && (c.touched || this.submitted()); }
  submit(): void { this.submitted.set(true); this.form.markAllAsTouched(); if (this.form.invalid) return; const v = this.form.getRawValue(); const message = `Bonjour Zakiya Bio,\n\nJe suis ${v.firstName} ${v.lastName}.\nSujet : ${v.subject}\nMessage : ${v.message}\nE-mail : ${v.email}${v.phone ? `\nTéléphone : ${v.phone}` : ''}`; window.open(buildWhatsAppUrl(message), '_blank', 'noopener'); }
}
