import { Article } from './article.model';

const img = (name: string) => `/assets/images/products/${name}`;

export const ARTICLES: Article[] = [
  { id: 1, slug: 'mon-pot-epices', name: "Mon Pot d’Épices", shortDescription: 'Un mélange aromatique pour relever vos plats du quotidien.', description: 'Une sélection d’épices réunies dans un mélange pratique et savoureux, pensé pour accompagner viandes, sauces, marinades et plats mijotés.', category: 'Saveurs', images: [img('mon-pot-epices.jpg'), img('melange-epices.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: true, badge: 'Coup de cœur', available: true },
  { id: 2, slug: 'huile-fourmi', name: 'Huile de fourmi', shortDescription: 'Un soin corporel à intégrer à votre routine après épilation.', description: 'Une huile de soin destinée à l’entretien de la peau après épilation. Contactez-nous pour obtenir les conseils d’utilisation et vérifier la disponibilité.', category: 'Soins du corps', images: [img('huile-fourmi.jpg')], price: null, priceOnRequest: true, sizes: ['30 ml'], colors: [], featured: true, badge: 'Tendance', available: true },
  { id: 3, slug: 'savon-olive', name: "Savon à l’olive", shortDescription: 'Un savon doux pour une routine de soin quotidienne.', description: 'Savon à l’olive proposé pour nettoyer la peau en douceur. Pour connaître la composition exacte et les recommandations adaptées, contactez directement la boutique.', category: 'Savons', images: [img('savon-olive.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: true, badge: 'Nouveau', available: true },
  { id: 4, slug: 'huile-cade-vinaigre-cidre', name: 'Duo capillaire au cade', shortDescription: 'Huile de cade et vinaigre de cidre pour votre routine capillaire.', description: 'Un duo de produits pour compléter votre rituel capillaire. Demandez conseil à Zakiya Bio pour l’usage, la composition et la disponibilité.', category: 'Soins capillaires', images: [img('duo-capillaire-cade.jpg')], price: null, priceOnRequest: true, sizes: ['50 ml'], colors: [], featured: true, available: true },
  { id: 5, slug: 'lait-amande-douce', name: "Lait d’amande douce", shortDescription: 'Un lait cosmétique pour une routine peau tout en douceur.', description: 'Lait cosmétique à l’amande douce. La disponibilité et les informations complètes du produit sont confirmées sur demande.', category: 'Soins du corps', images: [img('lait-amande.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: true, available: true },
  { id: 6, slug: 'huile-mahalabiya', name: 'Huile Mahalabiya', shortDescription: 'Une huile traditionnellement associée aux soins au henné.', description: 'Huile de soin Mahalabiya proposée par Zakiya Bio. Contactez la boutique pour vérifier son utilisation, son format et sa disponibilité.', category: 'Soins capillaires', images: [img('huile-mahalabiya.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: true, badge: 'Coup de cœur', available: true },
  { id: 7, slug: 'costus-indien', name: 'Costus indien', shortDescription: 'Costus indien conditionné en sachet, en plusieurs formats.', description: 'Costus indien soigneusement conditionné. Les formats présentés peuvent varier selon les arrivages.', category: 'Bien-être', images: [img('costus-indien.jpg')], price: null, priceOnRequest: true, sizes: ['50 g', '100 g'], colors: [], featured: false, available: true },
  { id: 8, slug: 'nigelle-miel-huile', name: 'Sélection nigelle', shortDescription: 'Une sélection autour de la nigelle, du miel et de l’huile.', description: 'Un assortiment de produits à base de nigelle présenté en boutique. Demandez les références actuellement disponibles.', category: 'Bien-être', images: [img('selection-nigelle.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: false, available: true },
  { id: 9, slug: 'soubala', name: 'Soumbala', shortDescription: 'Un condiment traditionnel au goût marqué.', description: 'Soumbala conditionné en pot, à découvrir pour enrichir vos préparations culinaires.', category: 'Saveurs', images: [img('soumbala.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: false, available: true },
  { id: 10, slug: 'the-minceur', name: 'Thé vert aux plantes', shortDescription: 'Une infusion à base de thé vert et de plantes.', description: 'Préparation pour infusion à base de thé vert et de plantes. Consultez les informations figurant sur l’emballage avant utilisation.', category: 'Bien-être', images: [img('the-vert.jpg')], price: null, priceOnRequest: true, sizes: ['12 sachets'], colors: [], featured: false, available: true },
  { id: 11, slug: 'parfums-orientica', name: 'Parfums Orientica', shortDescription: 'Une sélection de senteurs aux caractères variés.', description: 'Une gamme de parfums Orientica en plusieurs senteurs. Contactez-nous pour découvrir les références disponibles.', category: 'Parfums', images: [img('parfums-orientica.jpg')], price: null, priceOnRequest: true, sizes: [], colors: ['Variées'], featured: false, badge: 'Tendance', available: true },
  { id: 12, slug: 'huile-coco', name: 'Huile de coco', shortDescription: 'Un incontournable polyvalent de la beauté naturelle.', description: 'Huile de coco proposée dans la sélection Zakiya Bio. Format et disponibilité à confirmer auprès de la boutique.', category: 'Huiles naturelles', images: [img('huile-coco.jpg')], price: null, priceOnRequest: true, sizes: [], colors: [], featured: false, available: true },
];
